services:
  editor:
    container_name: search_editor
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../:/app
      - ~/.ssh:/home/developer/.ssh:ro
      - ~/projects/faculty:/app/files/faculty:ro
    environment:
      - DATABASE_URL=postgres://siteuser:postgresewvraer@db:5432/my_db
    env_file:
      - .env
    command: |
      bash -c '
        tail -f /dev/null
      '
  app:
    container_name: search_app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../:/app
      - ~/projects/faculty:/app/files/faculty:ro
    working_dir: /app
    ports:
      - 5173:5173
    entrypoint: sh
    command: |
      -c "
        cd /app/src
        pnpm install
        pnpm run dev --host
      "
  db:
    container_name: search_db
    image: timescale/timescaledb-ha:pg17 
    environment:
      - POSTGRES_USER=siteuser
      - POSTGRES_PASSWORD=postgresewvraer
      - POSTGRES_DB=my_db
    volumes:
      # - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

volumes:
  db_data: